version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.5
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdbv1:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:5.1.0
    ports:
      - "3000:3000"
    links:
      - influxdb
    restart: always
    user: "104"

  mssql:
    container_name: mssql
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1234qwerASDF"
      ACCEPT_EULA: "Y"  


  telegraf:
    container_name: telegraf
    image: telegraf:1.6
    network_mode: "host"
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes: 
  influxdbv1:
  telegraf: